### ISSUE TITLE
feature request: allow specifying credentials inline in dynamic clients

### ISSUE THREAD

**Issue by kevpogo** [BoundaryML/baml#1001]
Hi!

# Context
Actually, when we add a LLM client in Typescript, we need to specify a path to the credentials json file.

# Proposal
For an industrialisation of our project, it must be safier and easyier to pass directly the json to the client.

# Code before
```Typescript
clientRegistry.addLlmClient(
  "GeminiFlash",
  "vertex-ai",
  {
    [...]
    credentials: "path/to/the/file"
  });
```

# Code proposal
```Typescript
clientRegistry.addLlmClient(
  "GeminiFlash",
  "vertex-ai",
  {
    [...]
    credentials: {
      "type": "service_account",
      "project_id": "foo",
      [...]
    }
  });
```

**Comment by hellovai** [comment]
This should already be supported!

Check out credentials_content on https://docs.boundaryml.com/docs/snippets/clients/providers/vertex

If that resolves your issue, feel free to close this out!

**Comment by kevpogo** [comment]
In the doc, there are `credentials_content` but for BAML Playground only. When I put my json in this field, it doesn't works.
The stacktrace say :
```
Error {
  context: "Failed to build request",
  source: "Service account not found"
}
```

**Comment by aksell** [comment]
I am not able to get credentials_content working with vertex-ai either. I get the same error as kevpogo

**Comment by sxlijin** [comment]
Update: we expect to fix this in 0.59.0, which will release #1009 and go out either this weekend or Monday

**Comment by aksell** [comment]
Just tested 0.59  and now using `GOOGLE_APPLICATION_CREDENTIALS_CONTENT` works like a charm, thank you!

**Comment by sxlijin** [comment]
Awesome to hear! FYI- you can also just pass it in as `GOOGLE_APPLICATION_CREDENTIALS` now; we'll detect if it's "JSON in a string" and parse it as JSON if so.

@kevpogo you should be able to pass in the contents of a credentials file as `credentials` when using `clientRegistry` now.

**Comment by kevpogo** [comment]
Yeah it works :) Thank you for your reactivity!

**Comment by kevpogo** [comment]
Yeah it works 🙂
Thank you for your reactivity!
