### ISSUE TITLE
Need of dark mode feature in docs.boundaryml.com

### ISSUE THREAD

**Issue by Parth4git** [BoundaryML/baml#1049]
Kindly assign this issue to me .I really want to work on this issue ,as I have experience of implementing this feature in website

**Comment by Parth4git** [comment]
@aaronvg  Can I work on this issue.

**Comment by aaronvg** [comment]
Hey there, we currently use Fern Docs for our documentation, and currently are not looking to switch to dark mode.

**Comment by Parth4git** [comment]
ok

**Comment by prrao87** [comment]
Is there anyway this request could be considered again? Some of us spend many hours reading the docs and like to view them in dark mode to reduce discomfort for the eyes. @aaronvg

**Comment by hellovai** [comment]
Yes! We can ship that this weekend! @seawatts
