### ISSUE TITLE
Support enums and literals in maps

### ISSUE THREAD

**Issue by aaronvg** [BoundaryML/baml#1050]

**Comment by miguelcsx** [comment]
Hi @aaronvg , I'm interested in working on this issue, could you assign it to me?

**Comment by aaronvg** [comment]
Hi @miguelcsx  can you join our Discord? https://discord.gg/BTNBeXGuaS 

I can assign it to you, but we can chat in more depth there as well on how to get things setup.

**Comment by hellovai** [comment]
@miguelcsx are you still working on this? I'd love include this in 0.67+ next monday (Nov 11)!
