### ISSUE TITLE
[BUG] When using 'openai-generic', you must specify a base_url

### ISSUE THREAD

**Issue by WoutDeRijck** [BoundaryML/baml#1082]
# Reproducing bug
I loaded Llama with vllm using:
`vllm serve meta-llama/Meta-Llama-3.1-8B-Instruct --dtype auto --api-key token-abc123 --max-model-len 12800 &`

Then added this to clients.baml as

```
client<llm> MyClient {

  provider "openai-generic"

  options {
    base_url "http://localhost:8000/v1"
    api_key "token-abc123"
    model "meta-llama/Meta-Llama-3.1-8B-Instruct"
    default_role "user"
  }
}
```
Used `client "openai-generic/meta-llama/Meta-Llama-3.1-8B-Instruct"` in the resume.baml function
And

```
test = await b.ExtractResumeTEST(resume)
print(test)
```

Resulted in 
> [BUG] When using 'openai-generic', you must specify a base_url

While it is specified!

I am able to query the model through
```
from openai import OpenAI
client = OpenAI(
    base_url="http://localhost:8000/v1",
    api_key="token-abc123",
)

completion = client.chat.completions.create(
  model="meta-llama/Meta-Llama-3.1-8B-Instruct",
  messages=[
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)
```

# Environment
I am working in Google Colab connected to an L4 GPU.

**Comment by WoutDeRijck** [comment]
I think the error originates from this (in engine/baml-runtime/src/internal/llm_client/primitive/openai/properties/generic.rs)

```
let base_url = properties
        .remove("base_url")
        .and_then(|v| v.as_str().map(|s| s.to_string()))
        .context("When using 'openai-generic', you must specify a base_url")?;
```

**Comment by aaronvg** [comment]
thanks for the report, looking into it now

**Comment by aaronvg** [comment]
can you paste your baml function? Or at least the way you declare the `client` ?

> Used client "openai-generic/meta-llama/Meta-Llama-3.1-8B-Instruct" in the resume.baml function

Can you try `client MyClient` in your function?

**Comment by aaronvg** [comment]
We have more details on the client "shorthand": `<provider>/<model-name>` https://docs.boundaryml.com/docs/snippets/clients/overview. This format doesn't work well with custom base_url implementations, so you'll need to refer to your client name in your function:

```
function A() -> string {
  client MyClient
  prompt #"..."#
 }
```

**Comment by WoutDeRijck** [comment]
This resolved the issue! 
Thank you
