### ISSUE TITLE
0.63.0 Auth not Included in Playground

### ISSUE THREAD

**Issue by camhendo** [BoundaryML/baml#1093]
Went to test some new prompts with 0.63.0 yesterday and kept getting errors for no api key (Including direct error below).

Details:
Have tried with my regular `azure-openai` provider and a fallback `openai` provider
> Tried setting all env variables manually and through env, nothing brings the key into the request itself.  

Looking at the raw curl request, there are not auth headers included anymore as of this update. 

Error in playground: 
```
InvalidAuthentication (401)
Request failed: {
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}


Check the webview network tab for more details. Command Palette -> Open webview developer tools. 
```

**Comment by hellovai** [comment]
hi @camhendo! can you share your client here? Do you include `api_key` in your options?

**Comment by camhendo** [comment]
@hellovai there ended up being a mismatch in my clients, you had the right intuition there. This one is on me!!!
