### ISSUE TITLE
Deno and yarn: Could not find npm package '@boundaryml/baml-win32-arm64-msvc' matching '0.67.0'.

### ISSUE THREAD

**Issue by maktouch** [BoundaryML/baml#1152]
Following the guide, it doesn't seem to work. I think there's something wrong with the artifact? It works when I downgrade by a lot. 

```
maktouch in ~/Developer/research λ deno install npm:@boundaryml/baml                
Add npm:@boundaryml/baml@0.67.0
error: Could not find npm package '@boundaryml/baml-win32-arm64-msvc' matching '0.67.0'.
```

**Comment by aaronvg** [comment]
which platform are you using? See if it works using `pnpm` to unblock. I'll take a look.

**Comment by maktouch** [comment]
OSX with M4 cpu

**Comment by maktouch** [comment]
- npm worked
- pnpm worked
- yarn didn't work
![CleanShot 2024-11-09 at 17 26 10@2x](https://github.com/user-attachments/assets/71483c84-40bc-4d4b-85ee-94cbe6c76a11)
- deno didn't work 
![CleanShot 2024-11-09 at 17 27 41@2x](https://github.com/user-attachments/assets/1e250a57-7a9d-48e0-b137-e6d393689d31)

```
ProductName:		macOS
ProductVersion:		15.1
BuildVersion:		24B2082
```

**Comment by aaronvg** [comment]
thanks, I'll get a patch for this going out in the next couple days!

**Comment by aaronvg** [comment]
https://github.com/BoundaryML/baml/pull/1173

**Comment by aaronvg** [comment]
can you try this again? At least yarn doesn't ask for those questions anymore

**Comment by sxlijin** [comment]
We've verified the fix on our side:

<img width="467" alt="image" src="https://github.com/user-attachments/assets/5f576f70-5a93-4e7b-8136-c3dcf7675e93">

<img width="753" alt="image" src="https://github.com/user-attachments/assets/021ee94c-3f98-41d8-b8f3-eb0504911bcd">

@maktouch can you confirm whether or not this works for you?

**Comment by aaronvg** [comment]
Confirmed works in deno by another user.
