### ISSUE TITLE
VS Code Plugin - Run test - Error as http://localhost:65104/chat/completions is always used.

### ISSUE THREAD

**Issue by lanluu** [BoundaryML/baml#1232]
After updating both VS Code and BAML Package (NPM) to 0.70.1:
**- At BAML Playground -> Run Test -> Error:**
  ```
Unspecified error code: 404 Request failed: http://localhost:65104/chat/completions
404 page not found
  ```
- If I turn the Option 'Raw cURL' on, it shows me the correct `curl -X POST 'http://my_server_with_ip/v1/chat/completions' ...`.
- It is noted that there is no change in my `clients.baml`.
- I also updated the version in `generators.baml` to `0.70.1`.
- In runtime, everything just works as usual.

As I cannot test the .baml file in design time, it is very hard to check whether the promp and result work properly. :-/

**Comment by lanluu** [comment]
I defined my client as below:
```
client<llm> Ollama_Default {
  provider "openai-generic"
  options {
    base_url "http://my_ip/v1"
    model "gemma2:latest"
    api_key "ollama"
  }
}
```

**Comment by aaronvg** [comment]
Can you set "baml.enablePlaygroundProxy" to false in vscode settings, relod window and try again?

**Comment by lanluu** [comment]
I am then receiving the following error:
```
Unable to run
Unspecified error code: 2 reqwest::Error { kind: Request, source: "JsValue(TypeError: Failed to fetch\nTypeError: Failed to fetch\n    at __wbg_fetch_1e4e8ed1f64c7e28 (https://file+.vscode-resource.vscode-cdn.net/Users/lanluu/.vscode/extensions/boundary.baml-extension-0.70.3/web-panel/dist/assets/baml_schema_build.js:2721:17)\n    at baml_schema_build.wasm.reqwest::wasm::client::js_fetch::h0464a60bde8984a3 (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[7888]:0x711ffb)\n    at baml_schema_build.wasm.reqwest::wasm::client::fetch::{{closure}}::h9bf1ba2d85296e6b (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[390]:0x1f2101)\n    at baml_schema_build.wasm.baml_runtime::internal::llm_client::primitive::request::make_request::{{closure}}::hcde9d23e9eef4e8d (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[423]:0x20fb3d)\n    at baml_schema_build.wasm.<baml_runtime::internal::llm_client::primitive::LLMPrimitiveProvider as baml_runtime::internal::llm_client::traits::WithStreamable>::stream::{{closure}}::ha7df66153003d20b (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[143]:0x333eb)\n    at baml_schema_build.wasm.baml_runtime::BamlRuntime::run_test::{{closure}}::{{closure}}::{{closure}}::h8f8c1d1e16c466b2 (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[150]:0x586ab)\n    at baml_schema_build.wasm.wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::h21d2fe4c4725431a (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[264]:0x1612f0)\n    at baml_schema_build.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h14ac1a8e653f20b2 (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[3819]:0x5c8f30)\n    at baml_schema_build.wasm.<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he8db59bb936c5ae1 (wasm://wasm/baml_schema_build.wasm-029c29ba:wasm-function[14144]:0x7acbc7)\n    at __wbg_adapter_41 (https://file+.vscode-resource.vscode-cdn.net/Users/lanluu/.vscode/extensions/boundary.baml-extension-0.70.3/web-panel/dist/assets/baml_schema_build.js:240:12))" }
```

**Comment by aaronvg** [comment]
i think this is an issue with our latest release. See if using 0.70.1 of the playground fixes it -- I'm working on a fix now!

**Comment by lanluu** [comment]
I did checked it -- surely that I am using 0.70.1. I am also using the latest version of BAML VS Plugin -- i think 0.70.3, as I could see in VS.

**Comment by aaronvg** [comment]
ah yes, for VSCode you'll want it to be 0.70.1 as well (there's a way to install a specific version in VSCode). Either way, willl hopefully have a fix out in the next hour or so

**Comment by lanluu** [comment]
Yo, it worked. But I had to reset the Option "baml.enablePlaygroundProxy" to `true`. Anyway, thank you very much for your hints.

**Comment by aaronvg** [comment]
Try out 0.70.4 and let me know if you still have issues there.

**Comment by asvintheguy** [comment]
I'm still running into the same issue, but for me I tried 0.70.4 and it's telling me I'm on VSCode Runtime Version 0.70.1, even though the extension itself says it is on 0.70.4:
![image](https://github.com/user-attachments/assets/ea7ccb70-289a-40eb-9c83-44c2ae6f66fc)

**Comment by aaronvg** [comment]
Is vscode on 0.70.4? Check the version on extensions tab. It is ok if it says runtime is 0.70.1

**Comment by aaronvg** [comment]
Make sure to reload the window after updating

**Comment by asvintheguy** [comment]
Yeah, I've re-opened the window and tried it on both cursor and vscode (I haven't installed it in the first place on vscode, so that was a fresh install).

**Comment by asvintheguy** [comment]
Here's my version on the extension tab:
![image](https://github.com/user-attachments/assets/35b9e4b9-f19e-4c82-8970-e630dc601366)

**Comment by aaronvg** [comment]
Which provider are you trying to call? It seems they are down with a 503

**Comment by asvintheguy** [comment]
I was trying my workplace api, which is up currently. It shouldn't be localhost, but an actual url to a custom openai endpoint.

**Comment by asvintheguy** [comment]
The curl command it generates is correct and works with postman, just not that url that is seen in the error.

**Comment by aaronvg** [comment]
Do you use a container to run vscode?

You can also try to set the "baml.enablePlaygroundProxy": false

**Comment by asvintheguy** [comment]
Not a container, and I'll try that

**Comment by asvintheguy** [comment]
Apologies, just tested it and yes it was my API, thank you for the help though!

**Comment by asvintheguy** [comment]
Apologies, just figured it out and yes it was my API, thank you for the help though!

**Comment by aaronvg** [comment]
no worries!

**Comment by lanluu** [comment]
Yes, the newest Version 7.0.5 worked well.
