### ISSUE TITLE
`Tokens(in/out)` is not exposed to python.

### ISSUE THREAD

**Issue by Sidd065** [BoundaryML/baml#1271]
Every sync BAML function call is logged in the console like this one:
```
Client: FLASH2 (gemini-2.0-flash-exp) - 7675ms. StopReason: "STOP". Tokens(in/out): 6500/571
```
However `raw.__str__()` for the same call returns:
```
Client: FLASH2 (gemini-2.0-flash-exp) - 7675ms. StopReason: "STOP".
```
Is this expected behaviour?

**Comment by aaronvg** [comment]
Fixed in https://github.com/BoundaryML/baml/pull/1277

**Comment by optivisionlab** [comment]
how to get token in/out with baml-py?

**Comment by aaronvg** [comment]
here is an example - https://github.com/BoundaryML/baml/blob/canary/integ-tests/python/tests/test_collector.py 

but it's in early alpha preview -- the interfaces might change soon! official release coming soon!
