### ISSUE TITLE
[BAM-60] [baml] Support baml import/export command

### ISSUE THREAD

**Issue by hellovai** [BoundaryML/baml#272]
Users should be able to run:
```
$> baml export -i MyFunction
Export complete!
Run: baml import <base64>
```

Which allows someone to copy and paste baml files and all the dependencies trivially.

<sub>[BAM-60](https://linear.app/gloo/issue/BAM-60/[baml]-support-baml-importexport-command)</sub>

**Comment by aaronvg** [comment]
import is done, export is missing
