### ISSUE TITLE
[language] [Idea] Validate an output field matches exactly from the input

### ISSUE THREAD

**Issue by aaronvg** [BoundaryML/baml#318]
Some users want to extract entities *exactly* / verbatim from the `input`. 

The language could enforce this by declaring which fields should actually be 100% present verbatim in the text. We can easily validate the fields match input exactly in the client, preventing more boilerplate.

For example
```
class A {
   property string @extract
```
Other names `@validateVerbatim`, `@isExact`, `@exactQuote`, `@exactMatch`

Unsure if this is yet a big problem with LLMs, but it may be a good resilience/robustness feature where you wouldn't wonder "what if". They seem to be really good at quoting exactly.

Other solutions is to show users which fields (at least in the analytics) have not been quoted verbatim. I.e. we detect which parts of your schema are generative vs extractive. This can be done in addition to feature described.

To make all fields @exactMatch by default perhaps we can have a global config, and then you can indicate which fields are generative with @generative. This is assuming your use-case is mostly for exact entity extraction.

**Comment by aaronvg** [comment]
We can add a potential `span<string>` type of sorts. CC from @hellovai 

Idea is the span has the part of the input you're interested in in the 2nd param.
span<string, input.query.sdfasdf | input.query.bar>.


Is this part of a larger Validation feature, or an actual new type (like span<string>)? What if someone wants to validate more complex things? Should we be adding validation for all kinds of types like numbers, strings, etc like Zod does?

**Comment by villagab4** [comment]
I would love the ability to extract substrings from input. Could solve much of the entity extraction issues around hallucination
