### ISSUE TITLE
Update docs for ollama

### ISSUE THREAD

**Issue by jayakumark** [BoundaryML/baml#700]
When client is sending to ollama running on another machine, its not working. it keeps saying model not found.

1. set ollama to listen on 0.0.0.0 on host1
2. modify client.baml

client<llm> MyClient {
  provider ollama
  options {
    model mixtral
    options {
      temperature 0
      base_url "http://host1:11434" // Default is 11434
      api_key "ollama"
    }
  }
}

PS C:\Users\anonuser\Source\functiontest> baml-cli generate
Generated 1 baml_client
PS C:\Users\anonuser\Source\functiontest> & C:/Users/anonuser/AppData/Local/miniconda3/python.exe c:/Users/anonuser/Source/functiontest/bamltest.py
Traceback (most recent call last):
  File "c:\Users\anonuser\Source\functiontest\bamltest.py", line 87, in <module>
    asyncio.run(main())
  File "C:\Users\anonuser\AppData\Local\miniconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\anonuser\AppData\Local\miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anonuser\AppData\Local\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\anonuser\Source\functiontest\bamltest.py", line 79, in main
    summary = await b.ExtractSummary(email_text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\anonuser\Source\functiontest\baml_client\client.py", line 78, in ExtractSummary
    return coerce(mdl, raw.parsed())
                       ^^^^^^^^^^^^
baml_py.BamlError: LLM call failed: LLMErrorResponse { client: "MyClient", model: None, prompt:<Removed> invocation_params: {"options": Object {"temperature": Number(0), "base_url": String("http://host1:11434"), "api_key": String("ollama")}, "model": String("mixtral")}, start_time: SystemTime { intervals: 133633615957031827 }, latency: 314.7287ms, message: "Request failed: {\"error\":{\"message\":\"model 'mixtral' not found, try pulling it first\",\"type\":\"api_error\",\"param\":null,\"code\":null}}\n", code: Other(404) }

**Comment by hellovai** [comment]
Thanks for the bug report! Just to confirm, are you able to make a curl to `http://host1:11434`? 

also FYI, you don't need an `api_key` when calling the ollama client (i believe).

**Comment by jkfnc** [comment]
Thanks for getting back so quick. The logs on other machine does not even show that a request is coming.

Yes, curl works.. , Even if i remove the api_key it does the same.

PS>curl http://host1:11434
Ollama is running

**Comment by hellovai** [comment]
thanks! i just looked at the error and it looks like the error isn't in communicating with the ollama service, but rather just in which models you have on ollama:

> Request failed: {"error":{"message":"model 'mixtral' not found, try pulling it first

have you already run this on 
```bash
PS> ollama run mixtral
```

The bug on our end is that that error message is attrociously hard to read

**Comment by hellovai** [comment]
Looking further, it looks like we also need to update the docs! We require the `base_url` to point to the openai version of the api: `/v1`. 

See: https://ollama.com/blog/openai-compatibility

Additionally, base_url needs to be in the top level options, not inner! i think our docs are actually wrong and we don't require the inner level options!

```
client MyClient {
  provider ollama
  options {
    base_url "http://host1:11434/v1" // Default is 11434
    model mixtral
    temperature 0
  }
}
```

This is how we parse out options FYI:
https://github.com/BoundaryML/baml/blob/canary/engine/baml-runtime/src/internal/llm_client/primitive/openai/properties/ollama.rs

**Comment by jkfnc** [comment]
yes, adding v1 and moving it out of options to one level up fixed it. thanks

**Comment by hellovai** [comment]
these docs are now up to date!

https://docs.boundaryml.com/docs/snippets/clients/providers/ollama
