### ISSUE TITLE
Google access token is printed on stdout when using vertex-ai

### ISSUE THREAD

**Issue by tomsquest** [BoundaryML/baml#845]
Hi,

Using a client with provider `vertex-ai` and credentials from a file, when running the function, then the Google access token is printed on stdout.

I don't know if this is coming from baml or from vertexai lib, or from...

## Code

```python
print("start")
b.ExtractBook(book_text)
print("end")
```

## Output

```
start
Access Token: ya29.c.c0...
end
```

## Client

```baml
client<llm> GeminiFlash {
  provider vertex-ai
  retry_policy Retries
  options {
    model gemini-1.5-flash-001
    project_id env.GCP_PROJECT_ID
    location env.GCP_PROJECT_LOCATION
    credentials env.GCP_CREDENTIALS_FILE
  }
}
```

**Comment by sxlijin** [comment]
Yikes! We’ll look into this ASAP, thanks for flagging.

**Comment by anish-palakurthi** [comment]
Sorry about that, should be resolved now!

**Comment by tomsquest** [comment]
Thanks!
