### ISSUE TITLE
bug: compound clients do insufficient compiler validation

### ISSUE THREAD

**Issue by sxlijin** [BoundaryML/baml#859]
User report via Slack connect: they have a `fallback` client where one of the clients doesn't actually exist, which causes prompt rendering to panic in `unreachable!`.

**Comment by sxlijin** [comment]
In the same vein, if the `fallback` has no clients, it also hits `unreachable`

**Comment by anish-palakurthi** [comment]
Also need to add syntax errors for unresolvable clients within fallbacks.
