### ISSUE TITLE
Fix ruby builds for bundler

### ISSUE THREAD

**Issue by hellovai** [BoundaryML/baml#913]
When doing a `gem install baml` we work correctly, but when doing it via gemspec files, we fail, as `bundler` expects certain architectures.

To support this, BAML must compile for all of these:
aarch64-linux, aarch64-linux-gnu, aarch64-linux-musl, arm-linux, arm-linux-gnu,
arm-linux-musl, arm64-darwin, x86-linux, x86-linux-gnu, x86-linux-musl, x86_64-darwin, x86_64-linux, x86_64-linux-gnu, x86_64-linux-musl

**Comment by sxlijin** [comment]
See #956
