### ISSUE TITLE
jsonish: more capable scoring in union discriminant selection

### ISSUE THREAD

**Issue by sxlijin** [BoundaryML/baml#949]
Coming from #934; tldr- because scoring for union discriminant selection switches solely on which candidate was least penalized, we can't use "quantity of information preserved" as a metric. `Flags` is obviously too complex to use as a scoring metric, we do need a scoring metric that is closed under recursive summation, but I suspect we'll run into more awkward situations along these lines.

links:

- [slack thread](https://gloo-global.slack.com/archives/C03KV1PJ6EM/p1726002259200149)
- #950 has a minimum repro

**Comment by hellovai** [comment]
This should be fixed now! We now check how many "defualt" values we use vs don't use and prefer information with less default values.
