### ISSUE TITLE
bug: users should be able to load env vars after importing baml_client

### ISSUE THREAD

**Issue by sxlijin** [BoundaryML/baml#961]
In both the Python and TS libraries, we currently eagerly instantiate the `baml_client` runtime singleton, which has the side effect of forcing users to load environment variables before importing baml_client.

The import order of baml_client should _not_ have any implications for users, and it isn't _that_ hard to solve this (the singleton should just be instantiated lazily).

[Art just ran face-first into this issue](https://discord.com/channels/1119368998161752075/1283878294600548468/1284268032100794378), and he's not the only one.

**Comment by hellovai** [comment]
thsi is now resolved: https://docs.boundaryml.com/docs/calling-baml/set-env-vars#modifying-env-variables-in-your-program

**Comment by zkurtz** [comment]
> thsi is now resolved: https://docs.boundaryml.com/docs/calling-baml/set-env-vars#modifying-env-variables-in-your-program

link is dead -- closest thing now might be https://docs.boundaryml.com/guide/development/environment-variables
